### ISSUE TITLE
PoweredUP.isWebBluetooth returns false when page is online

### ISSUE THREAD

**Issue by DanieleBenedettelli** [xpunsterx/poweredup-js#18]
I successfully developed an app using the poweredup.js library.
It works when I run the html locally, but when running it from my server, it can't even scan for BLE devices,
The function PoweredUP.isWebBluetooth returns false.

Can you help me?

**Comment by xpunsterx** [comment]
Perhaps you mean the [node-poweredup](https://github.com/nathankellenicki/node-poweredup/) library. This repository does not use this library. Try asking a question [here](https://github.com/nathankellenicki/node-poweredup/issues)
